"""empty message

Revision ID: ed15400db997
Revises: f18514ccd989
Create Date: 2019-11-09 05:34:23.267845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed15400db997'
down_revision = 'f18514ccd989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'hi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('hi', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
