"""empty message

Revision ID: f18514ccd989
Revises: 465ae045366a
Create Date: 2019-11-09 05:33:15.083425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18514ccd989'
down_revision = '465ae045366a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('hi', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'hi')
    # ### end Alembic commands ###
